openapi: 3.0.2
info:
  title: Cloud POI
  description: Cloud POI - Specifications
  version: v1.0
  contact:
    name: Rajendra Kumar
servers:
  - url: https://www.uat.fdmerchantservices.com
    description: UAT
tags:
  - name: Cloud Based Integration
    description: Cloud POI APIs

paths:
  /boardinggateway/boarding/auth/signin:
    post:
      tags:
        - Cloud Based Integration
      summary: Login API
      description: This API authenticates the external client with the unique credentials shared earlier as part of initial setup. This API respond back with a session token. This token is required in header of each subsequent API triggered by partner.
      operationId: login
      x-group-name: Cloud Based Integration
      x-proxy-name: Login
      x-default-example: Login Sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
            examples:
              Login Sample:
                $ref: "#/components/examples/LoginRq"
        required: true
      responses:
        '200':
          description:  "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response200"
        '402':
          description:  "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response402"
        '300':
          description:  "Request failure"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response300"
        '404':
          description:  "Not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response404"
        '500':
          description:  "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response500"
              

  /boardinggateway/cloudpoidp/PosPush/nonOpiProcessAmount:
    post:
      tags:
      - Cloud Based Integration
      summary: Payment API
      description: This API is used to send refund transaction request. Merchants needs to add session token received during login api call in the header of this API.
      operationId: nonOpiProcessAmount
      x-group-name: Cloud Based Integration
      x-proxy-name: Payment API
      x-default-example: Sample - SALE
      parameters:
      - {$ref: "#/components/parameters/ApiKeyHeader"}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NonOpiProcessAmountRequest"
            examples:
              Sample - SALE:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_SALE'
              Sample - SALE WITH LPM:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_LPM'
              Sample - PreAuth Sale:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_PREAUTHSALE'
              Sample - PreAuth Completion:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_PREAUTCOMPLETION'
              Sample - Refund:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_Refund'
              Sample - Void:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_Void'
              Sample - Emi Sale:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_EmiSale'
              Sample - Transaction Status Check:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_TransactionStatusCheck'
              Sample - Settlement Transacton:
                $ref: '#/components/examples/NonOpiProcessAmountRequest_SettlementTransaction'    
        required: true     
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Response"
              examples:
                Sample - SALE:
                  $ref: "#/components/examples/ResponseSALE" 
                Sample - SALE WITH LPM:
                  $ref: "#/components/examples/ResponseSALEWITHLPM"
                Sample - PreAuth Sale:
                  $ref: "#/components/examples/ResponsePreAuthSale"
                Sample - PreAuth Completion:
                  $ref: "#/components/examples/ResponsePreAuthCompletion"
                Sample - Refund:
                  $ref: "#/components/examples/ResponseRefund"
                Sample - Void:
                  $ref: "#/components/examples/ResponseVoid"
                Sample - Emi Sale:
                  $ref: "#/components/examples/ResponseEmiSale"
                Sample - Transaction Status Check:
                  $ref: "#/components/examples/ResponseTransactionStatusCheck"  
                Sample - Settlement Transacton:
                  $ref: "#/components/examples/ResponseSettlementTransacton"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Status401"
        "300":
          description: Request Failure
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Status300"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Status500"
        "502":
          description: Request Timed Out
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Status502"
        "404":
            description: Not Found
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Status404"
           
components:
  parameters:
    ApiKeyHeader:
      name: Authorization
      schema: {type: string, example: '0pMHhH9J0D3_P5yUJDsjGUWBcAzEquRT'}
      in: header
      required: true
      description: never expiring token for all apis
  schemas:
    Response:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
        data:
          type: object
          description: response info
          example:    { "functionCode": "00","source": null,"billingAmount": null,"invoiceNumber": "202251211","customerMobile": null,"billingCurrency": "INR","transactionId": "202202250834781",    "customerName": null, "respCode": "200","response": "SUCCESS","cardType": null,"rrn": null, "authCode": null, "merchantId": "470000095488827", "terminalId": "33878692",    "respMsg": "Transaction Success","amexSeNumber": "","emiTenure": "","emiInterestRate": "", "emiProcessingFee": "0",  "emiDiscAmt": "0.08",   "dccIndicator": "0",    "dccExchangeRate": "", "offlineFlag": "N", "cardLastNumber": "", "totalAmount": "10.00",   "merchantRefNumber": "Guru415",    "customerRefNumber": "33333333333",    "emiFlag": "",    "cardNumber": null,  "expDate": "",  "posEntryMode": "",  "walletType": "W0", "primaryId": "Guru415",  "custId": "220225121129",   "emiPerMonth": "0",    "tranDate": "22022022",   "tranTime": "",    "cardBin": null,    "tipAmount": null,    "settlementDetails": "",    "walletId": "W0"}
    AuthRequest:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
          description: user name
          example: "Testuser135"
        password:
          type: string
          description: password
          example: "Test@1234"

    Status200:
      type: object
      properties:
        statusCode:
          type: string
          example: "200"
          description:  status code
        message:
          type: string
          description: success message
          example: Success  
    Response200:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status200"
        data:
          type: object
          properties:
            token:
              type: string
              example: "Wl3iTXZWZVrhoqNIiFPNwLBYe32NyTvh"
            userName:
              type: string
              example: "Testuser135"
          description: response info

    Status402:
      type: object
      properties:
        statusCode:
          type: string
          description:  status code
          example: "402"
        message:
          type: string
          description: "Token not found"
          example: "Token not found"
    Response402:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status402"
    NonOpiProcessAmountRequest:
      required:
        - merchantId
        - ain
        - terminalId
        - merchantRefNumber
        - authAmount
        - totalAmount
        - tranCurrency
        - reqDate
        - reqTime
        - mrchCountryCode
      properties:
        merchantId:
         type: string
         maxLength: 15
         minLength: 15
         description: Merchant ID assigned
         example: "470000050790214"
        ain:
         type: string
         maxLength: 7
         minLength: 7
         description: Acquirer institution number
         example: "4700000"
        functionCode:
         type: string
         maxLength: 02
         minLength: 02
         description: 00 = "Sale"  - Digital and Card
          01 = "Sale" - Card
          02 = "Preauth"
          03 = "Preauth Completion
          04 = "Refund"
          05 = "Void"
          08 = "EMI Sale"
          11 = "Transaction Status Check" (Inquiry)
          12 = "Settlement"
         example: "01" 
        terminalId:
         type: string
         maxLength: 8
         minLength: 8
         description: Terminal Id
         example: "62850698" 
        merchantRefNumber:
         type: string
         maxLength: 14
         minLength: 14
         description: Unique number for each transaction. Inquiry transaction should have same MRN of original txn
         example: "12345678900987"
        customerRefNumber:
         type: string
         maxLength: 20
         minLength: 20
         description: Consumer Number
         example: "12345678900987654321"
        authAmount:
         type: string
         maxLength: 19
         minLength: 0
         description: Bill Amount including decimal (ex 50.00 for $50 sale). Send 0.00 for inquiry txn
         example: "50.05"
        convFee:
         type: string
         description: Central GST Including decimal (Ex:- "10.00" for $10 cgst)
         example: "10.05"
        sgst:
         type: string
         description: State GST Including decimal (Ex:- "100.00" for $10 sgst)
         example: "100.00"
        igst:
         type: string
         description: State GST Including decimal (Ex:- "10.00" for $10 igst
         example: "10.05"
        cgst:
         type: string
         description: Central GST Including decimal (Ex:- "10.00" for $10 cgst)
         example: "50.05"
        totalAmount:
         type: string
         description: Total Amount (auth, fee, gsts) including decimal ((Ex:- "57.00" for $57 sale)
         example: "57.00"
        tranCurrency:
         type: integer
         maxLength: 3
         minLength: 3
         description: Transaction Currency Code (3-digit numeric value)
         example: 126
        reqDate:
         type: string
         description: Transaction initiated Date(DDMMYYYY) 
         example: "28022022"
        reqTime:
         type: string
         description: Transaction initiated Time(HHMMSS)
         example: "013034"
        tranDate:
         type: string
         description: Original transaction  Date(DDMMYYYY) 
         example: "28022022"
        tranTime:
         type: string
         description: Original transaction  Time(HHMMSS)
         example: "013034"
        invoiceNumber:
         type: string
         maxLength: 20
         minLength: 20
         description: Must pass the same value as original transaction
         example: "12345678900987654321"
        authCode:
         type: string
         maxLength: 6
         minLength: 6
         description: Must pass the same value received in original transaction response
         example: "123456"
        cardLastNumber:
         type: string
         maxLength: 4
         minLength: 4
         description: Last 4 Digits of Card Number
         example: "1234"
        cardBin:
         type: string
         description: First six digits of the Card, used in the original (sale) transaction
         example: "8456"
        callbackURL:
         type: string
         description: Response URL, place holder for notification API call feature)
         example: ""
        mrchCountryCode:
         type: string
         maxLength: 3
         minLength: 3
         description: Merchant Country Code (3-digit numeric value)
         example: "356"
        tranType:
         type: string
         maxLength: 50
         minLength: 0
         description: Transaction Description
         example: "sale"
        rrn:
         type: string
         description: Must pass the same value received in original transaction response
         example: ""
        udf1:
         type: string
         description: User Defined Field
         example: ""
        udf2:
         type: string
         description: User Defined Field
         example: ""
        emiTenure:
         type: string
         description: EMI duration
         example: ""
        paramList:
          type: array
          items:
            $ref: "#/components/schemas/Params"
    Params:
      type: object
      properties:
        param_lit:
          type: string
          description: kparam_lit
          example: "param 2 key"
        param:
          type: string
          description: param
          example: "54"
    Status:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          example: 200
          description:  status code
        message:
          type: string
          description: success message
          example: Success
    Status401:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          example: 401
          description:  status code
        message:
          type: string
          description: Token not found
          example: Token not found
    Status300:
      type: object
      properties:
        statusCode:
          type: integer
          description:  status code
          example: "300"
        message:
          type: string
          description: "Request Failure"
          example: "Request Failure"
    Response300:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status300"
    Status404:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          description: status code
          example: "404"
        message:
          type: string
          description: "Not Found"
          example: "Not Found"
    Response404:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status404"
     
    Status500:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          description: status code
          example: "500"
        message:
          type: string
          description: "Internal Server Error"
          example: "Internal Server Error"
    Response500:
        type: object
        properties:
         status:
          $ref: "#/components/schemas/Status500"
    Status502:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          description:  status code
          example: "502"
        message:
          type: string
          description: "Request Timed Out"
          example: "Request Timed Out"
    Response502:
        type: object
        properties:
         status:
          $ref: "#/components/schemas/Status502"
    Status1:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
          example: 402
          description:  status code
        message:
          type: string
          description: Bad Credential
          example: 'Bad Credential'
  examples:
    NonOpiProcessAmountRequest_SALE:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585547594'
            terminalId: '85547596'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '01'
            customerRefNumber: '2511202203112022031'
            merchantRefNumber: '2511202203112022031120220311202203112022031121323'
            transactionId: '202211250950162'
            reqDate: '25112022'
            reqTime: '144955'
            originalTranDate: ''
            originalTranTime: ''
            authCode: ''
            rrn: ''
            tokenId: ''
            invoiceNumber: ''
            batchNo: ''
            amexSeNumber: ''
            posEntryMode: ''
            walletType: ''
            walletId: ''
            schemeId: ''
            cardLastNumber: ''
            primaryId: ''
            customerName: ''
            offlineFlag: ''
            aTC: ''
            tVR: ''
            appLabel: ''
            aID: ''
            panSeqNo: ''
            schemeTranInfo: ''
            isInternalCall: null
            authenticationMethod: null
          amounts:
            authAmount: '56.39'
            mrchDiscountAmt: '.10'
            convFee: '.10'
            cgst: ''
            igst: ''
            sgst: ''
            gst: '.10'
            totalAmount: '56.59'
            tranCurrency: '036'
            tip: ''
          additionalParams:
            udf1: '23133'
            udf2: '21313'
            callbackURL: ''
            paramList:
              - param: '23'
                param_lit: param1 key
              - param: '54'
                param_lit: param 2 key
        
        


    NonOpiProcessAmountRequest_LPM:
      value:
       request:
         merchantDetails:
           ain: '2100000'
           billerId: '14'
           merchantId: '42298585547594'
           terminalId: '85547596'
           mrchCountryCode: '036'
           siteId: ''
           workStationId: ''
         txnDetails:
           functionCode: '00'
           customerRefNumber: '2511202203112022031'
           merchantRefNumber: '2511202203112022031120220311202203112022031121323'
           transactionId: '202211250950162'
           reqDate: '25112022'
           reqTime: '144955'
           originalTranDate: ''
           originalTranTime: ''
           authCode: ''
           rrn: ''
           tokenId: ''
           invoiceNumber: ''
           batchNo: ''
           amexSeNumber: ''
           posEntryMode: ''
           walletType: ''
           walletId: ''
           schemeId: ''
           cardLastNumber: ''
           primaryId: ''
           customerName: ''
           offlineFlag: ''
           aTC: ''
           tVR: ''
           appLabel: ''
           aID: ''
           panSeqNo: ''
           schemeTranInfo: ''
           isInternalCall: null
           authenticationMethod: null
         amounts:
           authAmount: '56.39'
           mrchDiscountAmt: '.10'
           convFee: '.10'
           cgst: ''
           igst: ''
           sgst: ''
           gst: '.10'
           totalAmount: '56.59'
           tranCurrency: '036'
           tip: ''
         additionalParams:
           udf1: '23133'
           udf2: '21313'
           callbackURL: ''
           paramList:
             - param: '23'
               param_lit: param1 key
             - param: '54'
               param_lit: param 2 key
       
  
    NonOpiProcessAmountRequest_PREAUTHSALE:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585547594'
            terminalId: '85547596'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '02'
            customerRefNumber: '2511202203112022031'
            merchantRefNumber: '2511202203112022031120220311202203112022031121323'
            transactionId: '202211250950162'
            reqDate: '25112022'
            reqTime: '144955'
            originalTranDate: ''
            originalTranTime: ''
            authCode: ''
            rrn: ''
            tokenId: ''
            invoiceNumber: ''
            batchNo: ''
            amexSeNumber: ''
            posEntryMode: ''
            walletType: ''
            walletId: ''
            schemeId: ''
            cardLastNumber: ''
            primaryId: ''
            customerName: ''
            offlineFlag: ''
            aTC: ''
            tVR: ''
            appLabel: ''
            aID: ''
            panSeqNo: ''
            schemeTranInfo: ''
            isInternalCall: null
            authenticationMethod: null
          amounts:
            authAmount: '56.39'
            mrchDiscountAmt: '.10'
            convFee: '.10'
            cgst: ''
            igst: ''
            sgst: ''
            gst: '.10'
            totalAmount: '56.59'
            tranCurrency: '036'
            tip: ''
          additionalParams:
            udf1: '23133'
            udf2: '21313'
            callbackURL: ''
            paramList:
              - param: '23'
                param_lit: param1 key
              - param: '54'
                param_lit: param 2 key
        
    NonOpiProcessAmountRequest_PREAUTCOMPLETION:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585549376'
            terminalId: '85549376'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '03'
            customerRefNumber: ''
            merchantRefNumber: VinayAMEX111347112022031119911111431
            transactionId: '202211250040180'
            reqDate: '21112022'
            reqTime: '150155'
            originalTranDate: '17112022'
            originalTranTime: ''
            authCode: '041232'
            rrn: '232122006000'
            tokenId: ''
            invoiceNumber: '10'
            batchNo: ''
            amexSeNumber: ''
            posEntryMode: ''
            walletType: ''
            walletId: ''
            schemeId: ''
            cardLastNumber: '1234'
            primaryId: ''
            customerName: ''
            offlineFlag: ''
            aTC: ''
            tVR: ''
            appLabel: ''
            aID: ''
            panSeqNo: ''
            schemeTranInfo: ''
            isInternalCall: 'N'
            authenticationMethod: null
          amounts:
            authAmount: '56.59'
            mrchDiscountAmt: ''
            convFee: ''
            cgst: ''
            igst: ''
            sgst: ''
            gst: ''
            totalAmount: '56.59'
            tranCurrency: '036'
            tip: ''
          additionalParams:
            udf1: ''
            udf2: ''
            callbackURL: ''
            paramList:
              - param: ''
                param_lit: ''
        
    NonOpiProcessAmountRequest_Refund:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585549376'
            terminalId: '85549376'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '04'
            customerRefNumber: ''
            merchantRefNumber: VinayVISA111347112022031119911111494
            transactionId: '202211257151105'
            reqDate: '25112022'
            reqTime: '125600'
            originalTranDate: '17112022'
            originalTranTime: '125401'
            authCode: '353319'
            rrn: '000000000095'
            tokenId: ''
            invoiceNumber: '10'
            batchNo: ''
            amexSeNumber: ''
            posEntryMode: ''
            walletType: ''
            walletId: ''
            schemeId: ''
            cardLastNumber: ''
            primaryId: ''
            customerName: ''
            offlineFlag: ''
            aTC: ''
            tVR: ''
            appLabel: ''
            aID: ''
            panSeqNo: ''
            schemeTranInfo: ''
            isInternalCall: null
          amounts:
            authAmount: '22.00'
            mrchDiscountAmt: ''
            convFee: ''
            cgst: ''
            igst: ''
            sgst: ''
            gst: ''
            totalAmount: '22.00'
            tranCurrency: '036'
            tip: ''
          additionalParams:
            udf1: ''
            udf2: ''
            callbackURL: ''
            paramList:
              - param: ''
                param_lit: ''
        
    NonOpiProcessAmountRequest_Void:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298519014704'
            terminalId: '19014704'
            mrchCountryCode: '036'
          txnDetails:
            functionCode: '05'
            merchantRefNumber: '900000700012'
            transactionId: '202211172224141'
            reqDate: '17112022'
            reqTime: '154900'
            originalTranDate: '14022022'
            originalTranTime: '133955'
            authCode: '318861'
            rrn: '232110980240'
            tokenId: null
            isInternalCall: 'Y'
            invoiceNumber: '4'
          amounts:
            totalAmount: '3'
            tranCurrency: '036'
            authAmount: '100.00'
        
    NonOpiProcessAmountRequest_EmiSale:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585547594'
            terminalId: '85547596'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '08'
            customerRefNumber: '2511202203112022031'
            merchantRefNumber: '2511202203112022031120220311202203112022031121323'
            transactionId: '202211250950162'
            reqDate: '25112022'
            reqTime: '144955'
            originalTranDate: ''
            originalTranTime: ''
            authCode: ''
            rrn: ''
            tokenId: ''
            invoiceNumber: ''
            batchNo: ''
            amexSeNumber: ''
            posEntryMode: ''
            walletType: ''
            walletId: ''
            schemeId: ''
            cardLastNumber: ''
            primaryId: ''
            customerName: ''
            offlineFlag: ''
            aTC: ''
            tVR: ''
            appLabel: ''
            aID: ''
            panSeqNo: ''
            schemeTranInfo: ''
            isInternalCall: null
            authenticationMethod: null
          amounts:
            authAmount: '56.39'
            mrchDiscountAmt: '.10'
            convFee: '.10'
            cgst: ''
            igst: ''
            sgst: ''
            gst: '.10'
            totalAmount: '56.59'
            tranCurrency: '036'
            tip: ''
          additionalParams:
            udf1: '23133'
            udf2: '21313'
            callbackURL: ''
            paramList:
              - param: '23'
                param_lit: param1 key
              - param: '54'
                param_lit: param 2 key
        
    NonOpiProcessAmountRequest_TransactionStatusCheck:
      value:
        request:
          merchantDetails:
            billerId: '14'
            ain: '2100000'
            merchantId: '42298585549376'
            terminalId: '85549376'
            mrchCountryCode: '036'
          txnDetails:
            functionCode: '11'
            merchantRefNumber: '111347112022031119911111494'
            reqDate: '03112022'
            reqTime: '134201'
            originalTranDate: '25112022'
            originalTranTime: '104523'
          amounts:
            authAmount: '36.79'
            totalAmount: '36.79'
            tranCurrency: '036'
          additionalParams:
            callbackURL: ''
            udf1: ''
            udf2: ''
            paramList:
              - param_lit: ''
                param: ''
        
        
    NonOpiProcessAmountRequest_SettlementTransaction:
      value:
        request:
          merchantDetails:
            ain: '2100000'
            billerId: '14'
            merchantId: '42298585547594'
            terminalId: '85547596'
            mrchCountryCode: '036'
            siteId: ''
            workStationId: ''
          txnDetails:
            functionCode: '12'
            customerRefNumber: '2511202203112022031'
            merchantRefNumber: '2511202203112022031120220311202203112022031121323'
            reqDate: '25112022'
            reqTime: '144955'
        
    ResponseSettlementTransacton:
      value:
        data:
            response:
              merchantDetails:
                ain: '2100000'
                billerId: '14'
                merchantId: '42298585547594'
                terminalId: '85547596'
                mrchCountryCode: '036'
                siteId: ''
                workStationId: ''
              txnStatus:
                respCode: '200'
                response: SUCCESS
                respMsg: SETTLEMENT ACCEPTED
              txnDetails:
                functionCode: '12'
                customerRefNumber: ''
                merchantRefNumber: ''
                transactionId: ''
                reqDate: '29112022'
                reqTime: '134901'
                originalTranDate: ''
                originalTranTime: ''
                authCode: ''
                rrn: ''
                tokenId: ''
                invoiceNumber: ''
                batchNo: ''
                amexSeNumber: ''
                posEntryMode: ''
                walletType: ''
                walletId: ''
                schemeId: ''
                cardLastNumber: ''
                primaryId: ''
                customerName: ''
                offlineFlag: ''
                aTC: ''
                tVR: ''
                appLabel: ''
                aID: ''
                panSeqNo: ''
                schemeTranInfo: ''
                isInternalCall: null
                authenticationMethod: null
              amounts:
                authAmount: ''
                mrchDiscountAmt: ''
                convFee: ''
                cgst: ''
                igst: ''
                sgst: ''
                gst: ''
                totalAmount: ''
                tranCurrency: ''
                tip: ''
              dccInfo:
                dccIndicator: ''
                dccCurrency: ''
                dccAmount: ''
                dccExchangeRate: ''
            
    ResponseSALE:
      value:
        data:
           response:
             merchantDetails:
               ain: '2100000'
               billerId: '14'
               merchantId: '42298585547594'
               terminalId: '85547596'
               mrchCountryCode: '036'
               siteId: ''
               workStationId: ''
             txnStatus:
               respCode: '200'
               response: SUCCESS
               respMsg: Transaction Success
             txnDetails:
               functionCode: '01'
               customerRefNumber: '2511202203112022031'
               merchantRefNumber: '2511202203112022031120220311202203112022031121323'
               transactionId: '202211250950162'
               reqDate: '25112022'
               reqTime: '144955'
               originalTranDate: ''
               originalTranTime: ''
               authCode: '015108'
               rrn: '232907066550'
               tokenId: '855475962511000002000040172756'
               invoiceNumber: '23'
               batchNo: '001'
               amexSeNumber: ''
               posEntryMode: INSERT
               walletType: ''
               walletId: ''
               schemeId: VISA CARD
               cardLastNumber: '0025'
               primaryId: ''
               customerName: CARD 2/VISA TEST
               offlineFlag: 'N'
               aTC: 01BA
               tVR: '8080008000'
               appLabel: VISA TEST
               aID: A0000000031010
               panSeqNo: '01'
               schemeTranInfo: 00000000Y26232965026672600000005
               isInternalCall: null
               authenticationMethod: OnlinePIN
             amounts:
               authAmount: '56.39'
               mrchDiscountAmt: '.10'
               convFee: '.10'
               cgst: ''
               igst: ''
               sgst: ''
               gst: '.10'
               totalAmount: '56.59'
               tranCurrency: '036'
               tip: ''
             dccInfo:
               dccIndicator: '0'
               dccCurrency: ''
               dccAmount: ''
               dccExchangeRate: ''
            
           
    ResponseSALEWITHLPM:
      value:
        data:
           response:
             merchantDetails:
               ain: '2100000'
               billerId: '14'
               merchantId: '42298585547594'
               terminalId: '85547596'
               mrchCountryCode: '036'
               siteId: ''
               workStationId: ''
             txnStatus:
               respCode: '200'
               response: SUCCESS
               respMsg: Transaction Success
             txnDetails:
               functionCode: '00'
               customerRefNumber: '2511202203112022031'
               merchantRefNumber: '2511202203112022031120220311202203112022031121323'
               transactionId: '202211250950162'
               reqDate: '25112022'
               reqTime: '144955'
               originalTranDate: ''
               originalTranTime: ''
               authCode: '015108'
               rrn: '232907066550'
               tokenId: '855475962511000002000040172756'
               invoiceNumber: '23'
               batchNo: '001'
               amexSeNumber: ''
               posEntryMode: INSERT
               walletType: ''
               walletId: ''
               schemeId: VISA CARD
               cardLastNumber: '0025'
               primaryId: ''
               customerName: CARD 2/VISA TEST
               offlineFlag: 'N'
               aTC: 01BA
               tVR: '8080008000'
               appLabel: VISA TEST
               aID: A0000000031010
               panSeqNo: '01'
               schemeTranInfo: 00000000Y26232965026672600000005
               isInternalCall: null
               authenticationMethod: OnlinePIN
             amounts:
               authAmount: '56.39'
               mrchDiscountAmt: '.10'
               convFee: '.10'
               cgst: ''
               igst: ''
               sgst: ''
               gst: '.10'
               totalAmount: '56.59'
               tranCurrency: '036'
               tip: ''
             dccInfo:
               dccIndicator: '0'
               dccCurrency: ''
               dccAmount: ''
               dccExchangeRate: ''
           
    ResponsePreAuthSale:
      value:
        data:
           response:
             merchantDetails:
               ain: '2100000'
               billerId: '14'
               merchantId: '42298585547594'
               terminalId: '85547596'
               mrchCountryCode: '036'
               siteId: ''
               workStationId: ''
             txnStatus:
               respCode: '200'
               response: SUCCESS
               respMsg: Transaction Success
             txnDetails:
               functionCode: '02'
               customerRefNumber: '2511202203112022031'
               merchantRefNumber: '2511202203112022031120220311202203112022031121323'
               transactionId: '202211250950162'
               reqDate: '25112022'
               reqTime: '144955'
               originalTranDate: ''
               originalTranTime: ''
               authCode: '015108'
               rrn: '232907066550'
               tokenId: '855475962511000002000040172756'
               invoiceNumber: '23'
               batchNo: '001'
               amexSeNumber: ''
               posEntryMode: INSERT
               walletType: ''
               walletId: ''
               schemeId: VISA CARD
               cardLastNumber: '0025'
               primaryId: ''
               customerName: CARD 2/VISA TEST
               offlineFlag: 'N'
               aTC: 01BA
               tVR: '8080008000'
               appLabel: VISA TEST
               aID: A0000000031010
               panSeqNo: '01'
               schemeTranInfo: 00000000Y26232965026672600000005
               isInternalCall: null
               authenticationMethod: OnlinePIN
             amounts:
               authAmount: '56.39'
               mrchDiscountAmt: '.10'
               convFee: '.10'
               cgst: ''
               igst: ''
               sgst: ''
               gst: '.10'
               totalAmount: '56.59'
               tranCurrency: '036'
               tip: ''
             dccInfo:
               dccIndicator: '0'
               dccCurrency: ''
               dccAmount: ''
               dccExchangeRate: ''
           
    ResponsePreAuthCompletion:
      value:
        data:
            response:
              merchantDetails:
                ain: '2100000'
                billerId: '14'
                merchantId: '42298585549376'
                terminalId: '85549376'
                mrchCountryCode: '036'
                siteId: ''
                workStationId: ''
              txnStatus:
                respCode: '200'
                response: SUCCESS
                respMsg: Transaction Success
              txnDetails:
                functionCode: '03'
                customerRefNumber: ''
                merchantRefNumber: ''
                transactionId: ''
                reqDate: '21112022'
                reqTime: '150155'
                originalTranDate: '17112022'
                originalTranTime: ''
                authCode: '353319'
                rrn: '000000000095'
                tokenId: ''
                invoiceNumber: ''
                batchNo: ''
                amexSeNumber: ''
                posEntryMode: ''
                walletType: ''
                walletId: ''
                schemeId: ''
                cardLastNumber: ''
                primaryId: ''
                customerName: ''
                offlineFlag: ''
                aTC: ''
                tVR: ''
                appLabel: ''
                aID: ''
                panSeqNo: ''
                schemeTranInfo: ''
                isInternalCall: null
                authenticationMethod: null
              amounts:
                authAmount: '56.59'
                mrchDiscountAmt: ''
                convFee: ''
                cgst: ''
                igst: ''
                sgst: ''
                gst: ''
                totalAmount: '56.59'
                tranCurrency: '036'
                tip: ''
              dccInfo:
                dccIndicator: ''
                dccCurrency: ''
                dccAmount: ''
                dccExchangeRate: ''
            
    ResponseRefund:
      value:
        data:
            response:
              merchantDetails:
                ain: '2100000'
                billerId: '14'
                merchantId: '42298585549376'
                terminalId: '85549376'
                mrchCountryCode: '036'
                siteId: ''
                workStationId: ''
              txnStatus:
                respCode: '200'
                response: SUCCESS
                respMsg: Transaction Success
              txnDetails:
                functionCode: '04'
                customerRefNumber: ''
                merchantRefNumber: VinayVISA111347112022031119911111494
                transactionId: '202211257151105'
                reqDate: '25112022'
                reqTime: '125600'
                originalTranDate: '17112022'
                originalTranTime: '125401'
                authCode: '353319'
                rrn: '000000000095'
                tokenId: ''
                invoiceNumber: '10'
                batchNo: ''
                amexSeNumber: ''
                posEntryMode: ''
                walletType: ''
                walletId: ''
                schemeId: ''
                cardLastNumber: ''
                primaryId: ''
                customerName: ''
                offlineFlag: ''
                aTC: ''
                tVR: ''
                appLabel: ''
                aID: ''
                panSeqNo: ''
                schemeTranInfo: ''
                isInternalCall: null
              amounts:
                authAmount: '22.00'
                mrchDiscountAmt: ''
                convFee: ''
                cgst: ''
                igst: ''
                sgst: ''
                gst: ''
                totalAmount: '22.00'
                tranCurrency: '036'
                tip: ''
              dccInfo:
                dccIndicator: ''
                dccCurrency: ''
                dccAmount: ''
                dccExchangeRate: ''
            
    ResponseVoid:
      value:
        data:
            response:
              merchantDetails:
                ain: '2100000'
                billerId: '14'
                merchantId: '42298519014704'
                terminalId: '19014704'
                mrchCountryCode: '036'
                siteId: ''
                workStationId: ''
              txnStatus:
                respCode: '200'
                response: ''
                respMsg: SUCCESS
              txnDetails:
                functionCode: '05'
                customerRefNumber: ''
                merchantRefNumber: ''
                transactionId: ''
                reqDate: '17112022'
                reqTime: '154900'
                originalTranDate: '14022022'
                originalTranTime: '133955'
                authCode: ''
                rrn: ''
                tokenId: ''
                invoiceNumber: ''
                batchNo: ''
                amexSeNumber: ''
                posEntryMode: ''
                walletType: ''
                walletId: ''
                schemeId: ''
                cardLastNumber: ''
                primaryId: ''
                customerName: ''
                offlineFlag: ''
                aTC: ''
                tVR: ''
                appLabel: ''
                aID: ''
                panSeqNo: ''
                schemeTranInfo: ''
                isInternalCall: null
              amounts:
                authAmount: '100.00'
                mrchDiscountAmt: ''
                convFee: ''
                cgst: ''
                igst: ''
                sgst: ''
                gst: ''
                totalAmount: '3'
                tranCurrency: '036'
                tip: ''
              dccInfo:
                dccIndicator: ''
                dccCurrency: ''
                dccAmount: ''
                dccExchangeRate: ''
            
    ResponseEmiSale:
      value:
        data:
            response:
              merchantDetails:
                ain: '2100000'
                billerId: '14'
                merchantId: '42298585547594'
                terminalId: '85547596'
                mrchCountryCode: '036'
                siteId: ''
                workStationId: ''
              txnStatus:
                respCode: '200'
                response: SUCCESS
                respMsg: Transaction Success
              txnDetails:
                functionCode: '08'
                customerRefNumber: '2511202203112022031'
                merchantRefNumber: '2511202203112022031120220311202203112022031121323'
                transactionId: '202211250950162'
                reqDate: '25112022'
                reqTime: '144955'
                originalTranDate: ''
                originalTranTime: ''
                authCode: '015108'
                rrn: '232907066550'
                tokenId: '855475962511000002000040172756'
                invoiceNumber: '23'
                batchNo: '001'
                amexSeNumber: ''
                posEntryMode: INSERT
                walletType: ''
                walletId: ''
                schemeId: VISA CARD
                cardLastNumber: '0025'
                primaryId: ''
                customerName: CARD 2/VISA TEST
                offlineFlag: 'N'
                aTC: 01BA
                tVR: '8080008000'
                appLabel: VISA TEST
                aID: A0000000031010
                panSeqNo: '01'
                schemeTranInfo: 00000000Y26232965026672600000005
                isInternalCall: null
                authenticationMethod: OnlinePIN
              amounts:
                authAmount: '56.39'
                mrchDiscountAmt: '.10'
                convFee: '.10'
                cgst: ''
                igst: ''
                sgst: ''
                gst: '.10'
                totalAmount: '56.59'
                tranCurrency: '036'
                tip: ''
              dccInfo:
                dccIndicator: '0'
                dccCurrency: ''
                dccAmount: ''
                dccExchangeRate: ''
            
    ResponseTransactionStatusCheck:
      value:
        data:
             response:
               merchantDetails:
                 ain: '2100000'
                 billerId: '14'
                 merchantId: '42298585549376'
                 terminalId: '85549376'
                 mrchCountryCode: '036'
                 siteId: ''
                 workStationId: ''
               txnStatus:
                 respCode: '200'
                 response: SUCCESS
                 respMsg: Transaction Success
               txnDetails:
                 functionCode: '11'
                 customerRefNumber: '123457772495'
                 merchantRefNumber: '111347112022031119911111494'
                 transactionId: '202211258230893'
                 reqDate: '03112022'
                 reqTime: '134201'
                 originalTranDate: '25112022'
                 originalTranTime: '104523'
                 authCode: '353319'
                 rrn: '232905064994'
                 tokenId: '855493762511000002000095161633'
                 invoiceNumber: '78'
                 batchNo: '001'
                 amexSeNumber: ''
                 posEntryMode: INSERT
                 walletType: ''
                 walletId: ''
                 schemeId: VISA CARD
                 cardLastNumber: '0176'
                 primaryId: ''
                 customerName: VISA ACQUIRER TEST/CARD 17
                 offlineFlag: 'N'
                 aTC: '0002'
                 tVR: '8080008000'
                 appLabel: VISA CREDIT
                 aID: A0000000031010
                 panSeqNo: ''
                 schemeTranInfo: 00000000E500000000353328XF340005
                 isInternalCall: null
                 authenticationMethod: unknownMethod
               amounts:
                 authAmount: '21.00'
                 mrchDiscountAmt: ''
                 convFee: ''
                 cgst: ''
                 igst: ''
                 sgst: ''
                 gst: ''
                 totalAmount: '45.20'
                 tranCurrency: AUD
                 tip: '1.20'
               dccInfo:
                 dccIndicator: '0'
                 dccCurrency: ''
                 dccAmount: ''
                 dccExchangeRate: ''
             
    ResponseDefault:
      value:
        data:
            functionCode: "00"
            source: null
            billingAmount: null
            invoiceNumber: "202251211"
            customerMobile: null
            billingCurrency: "INR"
            transactionId: "202202250834781"
            customerName: null
            respCode: "200"
            response: "SUCCESS"
            cardType: null
            rrn: null
            authCode: null
            merchantId: "470000095488827"
            terminalId: "33878692"
            respMsg: "Transaction Success"
            amexSeNumber: ""
            emiTenure: ""
            emiInterestRate: ""
            emiProcessingFee: "0"
            emiDiscAmt: "0.08"
            dccIndicator: "0"
            dccExchangeRate": ""
            offlineFlag: "N"
            cardLastNumber: ""
            totalAmount: "10.00"
            merchantRefNumber: "Guru415"
            customerRefNumber: "33333333333"
            emiFlag: ""
            cardNumber: null,
            expDate: ""
            posEntryMode: ""
            walletType: "W0"
            primaryId: "Guru15"
            custId: "220225121129"
            emiPerMonth: "0"
            tranDate: "22022022"
            tranTime: ""
            cardBin: null
            tipAmount: null
            settlementDetails: ""
            walletId: "W0"
    "401-Premier":
      value:
        messages: Token not found
    "300-Premier":
      value:
        messages: Request Failure
    "500-Premier":
      value:
        messages: Internal Server Error
    "404-Premier":
      value:
        messages: Not Found
    "502-Premier":
      value:
        messages: Request Timed Out
          
    LoginRq:
      value:
        username: "Testuser135"
        password: "Test@1234"
    LoginRs200:
      description: Request is successfully processed. Merchant should use the generated token and proceed with Payment API transaction Initiation.
      value:
        {
          "status": {
            "statusCode": "200",
            "message": "Success"
          },
          "data": {
            "token": "Wl3iTXZWZVrhoqNIiFPNwLBYe32NyTvh",
            "userName": "Testuser135"
          }
        }

    LoginRs402:
      description: "Invalid Credentials."
      value:
        {
          "status": {
            "statusCode": "402",
            "message": "Bad Credential"
          },
          "data": {}
        }
    LoginRs300:
      description: "Redirection error. Merchant should validate and retry with new request."
      value:
       {
          "status": {
            "statusCode": "300",
            "message": "Request failure"
          },
          "data": {}
        }
    LoginRs404:
      description: "Server cannot find the requested resource. Contact Customer Support / Business Manager."
      value:
       {
          "status": {
            "statusCode": "404",
            "message": "Not found"
          },
          "data": {}
        }
    LoginRs500:
      description: "Server Error. Contact Customer Support / Business Manager."
      value:
       {
          "status": {
            "statusCode": "500",
            "message": "Not found"
          },
          "data": {}
        }
  
